print('The documentation for the pyNetSocket library')
print('This covers all the information you need to start')
print('')
print('You can see the full guides here:')
print('https://github.com/DrSparky-2007/PyNetSocket/')
openLink = input('Open link in browser? (y/n) ')
